---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: con-2-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: con-2-pod
  template:
    metadata:
      labels:
        app: con-2-pod
    spec:
      containers:
        - image: blake2718/con2-mvp-3-13
          name: con-2-container
          env: 
            - name: QUEUE
              value: COLOR.BLUE
